vim.pack.add({ "https://github.com/nvim-treesitter/nvim-treesitter" })
require("nvim-treesitter").setup()
require("nvim-treesitter").install({
	"bash",
	"c",
	"diff",
	"ini",
	"json",
	"lua",
	"luadoc",
	"markdown",
	"markdown_inline",
	"odin",
	"python",
	"query",
	"regex",
	"rust",
	"toml",
	"vim",
	"vimdoc",
	"yaml",
})
